### ISSUE TITLE
useradd: invalid user ID 'pi'

### ISSUE THREAD

**Issue by ardinusawan** [loblab/noip-renew#12] opened 2020-03-07 16:56 UTC
When I try to running with docker, got this error.

```bash
pi@raspberrypi:~/Project/noip-renew $ docker-compose up
Building selenium
Step 1/16 : FROM debian
 ---> 756aa643c9cd
Step 2/16 : MAINTAINER loblab
 ---> Using cache
 ---> 7381898d26af
Step 3/16 : ARG USER=loblab
 ---> Using cache
 ---> ca78fdc41038
Step 4/16 : ARG UID=1000
 ---> Using cache
 ---> d88caef2dc81
Step 5/16 : ARG HOME=/noip-renew
 ---> Using cache
 ---> 1c07ec2921b3
Step 6/16 : ARG DEBIAN_FRONTED=noninteractive
 ---> Using cache
 ---> f016d280d84e
Step 7/16 : ARG PYTHON=python3
 ---> Using cache
 ---> c5d708450ccd
Step 8/16 : RUN apt-get update && apt-get -y upgrade
 ---> Using cache
 ---> 8515044e6267
Step 9/16 : RUN apt-get -y install chromium-chromedriver ||     apt-get -y install chromium-driver ||     apt-get -y install chromedriver
 ---> Using cache
 ---> 97fdad943338
Step 10/16 : RUN apt-get -y install ${PYTHON}-pip
 ---> Using cache
 ---> 88a396587817
Step 11/16 : RUN $PYTHON -m pip install selenium
 ---> Using cache
 ---> 65c569707967
Step 12/16 : RUN apt-get -y install curl wget
 ---> Using cache
 ---> 286983192a50
Step 13/16 : RUN useradd -d $HOME -u $UID $USER
 ---> Running in 4377b1a632f2
useradd: invalid user ID 'pi'
ERROR: Service 'selenium' failed to build: The command '/bin/sh -c useradd -d $HOME -u $UID $USER' returned a non-zero code: 3
```

**Comment by IDemixI** [comment] 2020-03-23 21:54
Hi @ardinusawan,

I'm not massively familiar with Docker but I believe that the useradd -u parameter is looking for a numeric id. Somehow it's grabbing "pi"? I would try swapping -u out for -U. Hopefully that fixes it!

**Comment by loblab** [comment] 2020-04-12 06:13
Hi @ardinusawan,

I didn't try docker on Pi yet although I have many Pis.

The $UID should be 1000, $USER should be pi (or other login name you renamed). Check the environment variables or try to export them explicitly before docker-compose up.

**Comment by Callum17** [comment] 2020-07-22 02:52
Callum17@5794362 was a fix for my Raspberry Pi 4 deployment

Pull request for a cleaner fix in. Caused by the UID docker-compose arg not being passed from the local env into the build. Guessing this is a problem unique to Raspberry PI?

Solution is to simply drop the args - as far as I can tell they are redundant.

**Comment by BK-STAR77** [comment] 2020-08-30 21:41
same issue with a seedbox with Ubuntu 20.04...

**Comment by loblab** [comment] 2021-01-02 00:03
Please try the latest version which merged the fix.

**Closed by loblab** 2021-01-02 00:03 UTC
